import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import './globals.css'
import AuthProvider from '@/context/AuthContext'
import CourseProvider from '@/context/CourseContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Course',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <CourseProvider>

          <body className={inter.className}>
            <ToastContainer hideProgressBar={true} autoClose={2500} />
            {children}
          </body>
        </CourseProvider>
      </AuthProvider>
    </html>
  )
}
